"""
Services package for system app
============================================================

This package contains all service classes organized by functionality.
Maintains backward compatibility by re-exporting all services.

Auto-generated by Service Separator
Date: 2025-10-18 23:47:47
"""
from __future__ import annotations

from .country_service import CountryService
from .app_config_service import AppConfigService
from .app_version_service import AppVersionService
from .app_update_service import AppUpdateService
from .app_health_service import AppHealthService

# Backward compatibility - all services available at package level
__all__ = [
    "AppConfigService",
    "AppHealthService",
    "AppUpdateService",
    "AppVersionService",
    "CountryService",
]
