"""
Service for AppUpdate operations
============================================================

This module contains service classes for service for appupdate operations.

Auto-generated by Service Separator
Date: 2025-10-18 23:47:47
"""
from __future__ import annotations

from __future__ import annotations
import logging
from typing import Any, Dict, List, Optional
from django.db import models
from django.db.models import Q
from django.utils import timezone
from django.core.cache import cache
from django.conf import settings
from django.db import connection
from packaging import version as version_parser
from api.common.services.base import BaseService, CRUDService, ServiceException
from api.system.models import Country, AppConfig, AppVersion, AppUpdate

class AppUpdateService(CRUDService):
    """Service for AppUpdate operations"""
    model = AppUpdate
    
    def get_recent_updates(self, limit: int = 5) -> List[AppUpdate]:
        """Get recent app updates"""
        return list(self.model.objects.all()[:limit])
    
    def get_updates_since_version(self, version_str: str) -> List[AppUpdate]:
        """Get all updates since a specific version"""
        try:
            updates = []
            all_updates = self.model.objects.all()
            
            for update in all_updates:
                if version_parser.parse(update.version) > version_parser.parse(version_str):
                    updates.append(update)
            
            return updates
            
        except Exception as e:
            self.log_error(f"Failed to get updates since version {version_str}: {str(e)}")
            return []
