"""
Service for country operations
============================================================

This module contains service classes for service for country operations.

Auto-generated by Service Separator
Date: 2025-10-18 23:47:47
"""
from __future__ import annotations

from typing import Optional
from django.db import models
from django.db.models import Q
from api.common.services.base import CRUDService
from api.system.models import Country

class CountryService(CRUDService):
    """Service for country operations"""
    model = Country
    
    def get_active_countries(self) -> models.QuerySet:
        """Get all active countries ordered by name"""
        try:
            return self.model.objects.filter(is_active=True).order_by('name')
        except Exception as e:
            self.handle_service_error(e, "Failed to get active countries")
    
    def search_countries(self, query: str) -> models.QuerySet:
        """Search countries by name or code"""
        try:
            return self.model.objects.filter(
                Q(name__icontains=query) | Q(code__icontains=query),
                is_active=True
            ).order_by('name')
        except Exception as e:
            self.handle_service_error(e, "Failed to search countries")
    
    def get_country_by_code(self, code: str) -> Optional[Country]:
        """Get country by code"""
        try:
            return self.model.objects.get(code=code, is_active=True)
        except self.model.DoesNotExist:
            return None
        except Exception as e:
            self.handle_service_error(e, f"Failed to get country: {code}")
