# Generated by Django 5.2.5 on 2025-10-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('rental', 'Rental'), ('payment', 'Payment'), ('promotion', 'Promotion'), ('system', 'System'), ('achievement', 'Achievement'), ('points', 'Points'), ('otp_sms', 'OTP SMS'), ('otp_email', 'OTP Email')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('rental', 'Rental'), ('payment', 'Payment'), ('promotion', 'Promotion'), ('system', 'System'), ('achievement', 'Achievement'), ('security', 'Security'), ('points', 'Points'), ('otp_sms', 'OTP SMS'), ('otp_email', 'OTP Email')], max_length=50),
        ),
    ]
