# Generated by Django 4.2.7 on 2025-10-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_update_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('rental', 'Rental'), ('payment', 'Payment'), ('promotion', 'Promotion'), ('system', 'System'), ('achievement', 'Achievement'), ('points', 'Points'), ('update', 'Update'), ('admin', 'Admin'), ('otp_sms', 'OTP SMS'), ('otp_email', 'OTP Email')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('rental', 'Rental'), ('payment', 'Payment'), ('promotion', 'Promotion'), ('system', 'System'), ('achievement', 'Achievement'), ('security', 'Security'), ('points', 'Points'), ('update', 'Update'), ('admin', 'Admin'), ('otp_sms', 'OTP SMS'), ('otp_email', 'OTP Email')], max_length=50),
        ),
    ]