# Generated by Django 5.2.5 on 2025-09-14 11:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateFeeConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Configuration name (e.g., 'Standard Late Fee')", max_length=100)),
                ('fee_type', models.CharField(choices=[('MULTIPLIER', 'Multiplier (e.g., 2x normal rate)'), ('FLAT_RATE', 'Flat rate per hour'), ('COMPOUND', 'Compound (multiplier + flat rate)')], default='MULTIPLIER', max_length=50)),
                ('multiplier', models.DecimalField(decimal_places=2, default=2.0, help_text='Multiplier value (e.g., 2.0 = 2x normal rate)', max_digits=5)),
                ('flat_rate_per_hour', models.DecimalField(decimal_places=2, default=0, help_text='Additional flat rate per overdue hour in NPR', max_digits=10)),
                ('grace_period_minutes', models.IntegerField(default=0, help_text='Grace period in minutes before charges apply')),
                ('max_daily_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum rate per day (optional cap)', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one configuration can be active per package type')),
                ('applicable_package_types', models.JSONField(default=list, help_text='List of package types this applies to (empty = all types)')),
                ('metadata', models.JSONField(default=dict, help_text='Additional configuration data')),
            ],
            options={
                'verbose_name': 'Late Fee Configuration',
                'verbose_name_plural': 'Late Fee Configurations',
                'db_table': 'late_fee_configurations',
                'ordering': ['-created_at'],
            },
        ),
    ]
