# Generated by Django 5.2.5 on 2025-09-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_update_late_fee_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaupload',
            name='cloud_provider',
            field=models.CharField(default='cloudinary', max_length=50),
        ),
        migrations.AddField(
            model_name='mediaupload',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='mediaupload',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
