"""
Points Services - Service Layer Exports
============================================================

This module exports all point-related services and universal API methods.

Auto-generated by Service Splitter
Date: 2025-10-15
"""

# Import service classes
from .points_service import PointsService
from .referral_service import ReferralService
from .points_leaderboard_service import PointsLeaderboardService

# Import UNIVERSAL API methods (recommended for most use cases)
from .points_api import (
    award_points,      # Universal sync/async points awarding
    deduct_points,     # Universal sync/async points deduction
    complete_referral, # Complete referral
)


__all__ = [
    # Service classes (for direct access if needed)
    "PointsService",
    "ReferralService",
    "PointsLeaderboardService",
    
    # UNIVERSAL API METHODS - Use these for clean, simple code!
    "award_points",      # award_points(user, points, source, desc, async_send=False)
    "deduct_points",     # deduct_points(user, points, source, desc, async_send=False)
    "complete_referral", # complete_referral(referral_id, async_send=True)
]
