"""
Admin Serializers
Auto-generated by split_serializer.py
"""

from __future__ import annotations
from api.admin.models import AdminActionLog
from rest_framework import serializers


class AdminLoginSerializer(serializers.Serializer):
    """Serializer for admin login"""
    email = serializers.EmailField()
    password = serializers.CharField(write_only=True)



class AdminPasswordUpdateSerializer(serializers.Serializer):
    """Serializer for updating admin password"""
    new_password = serializers.CharField(
        min_length=8,
        max_length=128,
        required=True,
        help_text="New password (minimum 8 characters)"
    )



class AdminActionLogSerializer(serializers.ModelSerializer):
    """Serializer for admin action logs"""
    admin_username = serializers.CharField(source='admin_user.username', read_only=True)
    admin_email = serializers.CharField(source='admin_user.email', read_only=True)
    
    class Meta:
        model = AdminActionLog
        fields = [
            'id', 'action_type', 'target_model', 'target_id', 'changes',
            'description', 'ip_address', 'user_agent', 'created_at',
            'admin_username', 'admin_email'
        ]
        read_only_fields = ['id', 'created_at']



class AdminKYCListSerializer(serializers.Serializer):
    """Serializer for KYC list filters"""
    status = serializers.ChoiceField(
        choices=['PENDING', 'APPROVED', 'REJECTED'],
        required=False
    )
    search = serializers.CharField(required=False)
    start_date = serializers.DateTimeField(required=False)
    end_date = serializers.DateTimeField(required=False)
    page = serializers.IntegerField(default=1, min_value=1)
    page_size = serializers.IntegerField(default=20, min_value=1, max_value=100)



class AdminKYCSerializer(serializers.Serializer):
    """Serializer for KYC submission details"""
    id = serializers.UUIDField(read_only=True)
    user_id = serializers.UUIDField(read_only=True)
    username = serializers.CharField(source='user.username', read_only=True)
    email = serializers.CharField(source='user.email', read_only=True)
    phone_number = serializers.CharField(source='user.phone_number', read_only=True)
    
    document_type = serializers.CharField(read_only=True)
    document_number = serializers.CharField(read_only=True)
    document_front_url = serializers.URLField(read_only=True)
    document_back_url = serializers.URLField(read_only=True)
    
    status = serializers.CharField(read_only=True)
    verified_at = serializers.DateTimeField(read_only=True)
    verified_by_username = serializers.CharField(source='verified_by.username', read_only=True, allow_null=True)
    rejection_reason = serializers.CharField(read_only=True, allow_null=True)
    
    created_at = serializers.DateTimeField(read_only=True)
    updated_at = serializers.DateTimeField(read_only=True)


