"""
Common Serializers
Auto-generated by split_serializer.py
"""

from __future__ import annotations
from api.admin.models import SystemLog
from api.common.models import LateFeeConfiguration
from decimal import Decimal
from rest_framework import serializers


class SystemLogSerializer(serializers.ModelSerializer):
    """Serializer for system logs"""
    level_display = serializers.CharField(source='get_level_display', read_only=True)
    
    class Meta:
        model = SystemLog
        fields = [
            'id', 'level', 'level_display', 'module', 'message', 
            'context', 'trace_id', 'created_at'
        ]
        read_only_fields = ['id', 'created_at']



class ToggleMaintenanceSerializer(serializers.Serializer):
    """Serializer for toggling maintenance mode"""
    is_maintenance = serializers.BooleanField()
    reason = serializers.CharField(max_length=500)



class RemoteCommandSerializer(serializers.Serializer):
    """Serializer for sending remote commands"""
    command = serializers.ChoiceField(choices=[
        'REBOOT', 'UNLOCK_SLOT', 'LOCK_SLOT', 'UPDATE_FIRMWARE',
        'SYNC_TIME', 'CLEAR_CACHE', 'RESET_HARDWARE'
    ])
    parameters = serializers.JSONField(default=dict)



class SystemHealthSerializer(serializers.Serializer):
    """Serializer for system health (response only)"""
    database_status = serializers.CharField()
    redis_status = serializers.CharField()
    celery_status = serializers.CharField()
    storage_status = serializers.CharField()
    response_time_avg = serializers.FloatField()
    error_rate = serializers.FloatField()
    uptime_percentage = serializers.FloatField()
    cpu_usage = serializers.FloatField()
    memory_usage = serializers.FloatField()
    disk_usage = serializers.FloatField()
    pending_tasks = serializers.IntegerField()
    failed_tasks = serializers.IntegerField()
    last_updated = serializers.DateTimeField()



class SystemLogFiltersSerializer(serializers.Serializer):
    """Serializer for system log filters"""
    level = serializers.ChoiceField(
        choices=SystemLog.LogLevelChoices.choices,
        required=False
    )
    module = serializers.CharField(required=False)
    search = serializers.CharField(required=False)
    start_date = serializers.DateTimeField(required=False)
    end_date = serializers.DateTimeField(required=False)
    page = serializers.IntegerField(default=1, min_value=1)
    page_size = serializers.IntegerField(default=50, min_value=1, max_value=200)



class RevenueOverTimeQuerySerializer(serializers.Serializer):
    """Query parameters for revenue over time analytics"""
    period = serializers.ChoiceField(
        choices=['daily', 'weekly', 'monthly'],
        required=True,
        help_text="Aggregation period: daily, weekly, or monthly"
    )
    start_date = serializers.DateField(
        required=False,
        help_text="Start date (default: 180 days ago)"
    )
    end_date = serializers.DateField(
        required=False,
        help_text="End date (default: today)"
    )
    transaction_type = serializers.ChoiceField(
        choices=['TOPUP', 'RENTAL', 'RENTAL_DUE', 'REFUND', 'FINE'],
        required=False,
        help_text="Filter by transaction type"
    )



class RevenueChartDataSerializer(serializers.Serializer):
    """Single data point for revenue chart"""
    date = serializers.DateField()
    label = serializers.CharField()
    total_revenue = serializers.FloatField()
    rental_revenue = serializers.FloatField()
    rental_due_revenue = serializers.FloatField()
    topup_revenue = serializers.FloatField()
    fine_revenue = serializers.FloatField()
    transaction_count = serializers.IntegerField()



class RevenueSummarySerializer(serializers.Serializer):
    """Summary statistics for revenue over time"""
    avg_per_period = serializers.FloatField()
    peak_month = serializers.CharField(allow_null=True)
    peak_revenue = serializers.FloatField()
    growth_rate = serializers.FloatField(allow_null=True)



class RevenueOverTimeResponseSerializer(serializers.Serializer):
    """Response format for revenue over time endpoint"""
    period = serializers.CharField()
    start_date = serializers.DateField()
    end_date = serializers.DateField()
    currency = serializers.CharField()
    total_revenue = serializers.FloatField()
    chart_data = RevenueChartDataSerializer(many=True)
    summary = RevenueSummarySerializer()



class LateFeeConfigurationSerializer(serializers.ModelSerializer):
    """Serializer for Late Fee Configuration listing and detail"""
    
    fee_type_display = serializers.CharField(source='get_fee_type_display', read_only=True)
    description_text = serializers.SerializerMethodField()
    
    class Meta:
        model = LateFeeConfiguration
        fields = [
            'id',
            'name',
            'fee_type',
            'fee_type_display',
            'multiplier',
            'flat_rate_per_hour',
            'grace_period_minutes',
            'max_daily_rate',
            'is_active',
            'applicable_package_types',
            'metadata',
            'description_text',
            'created_at',
            'updated_at'
        ]
        read_only_fields = ['id', 'created_at', 'updated_at', 'fee_type_display', 'description_text']
    
    def get_description_text(self, obj) -> str:
        """Get human-readable description of the fee structure"""
        return obj.get_description()



class CreateLateFeeConfigurationSerializer(serializers.Serializer):
    """Serializer for creating a new late fee configuration"""
    
    name = serializers.CharField(
        max_length=100,
        required=True,
        help_text="Clear name for this fee setting (e.g., 'Standard Late Fee')"
    )
    
    fee_type = serializers.ChoiceField(
        choices=LateFeeConfiguration.FEE_TYPE_CHOICES,
        default='MULTIPLIER',
        help_text="Fee calculation method: MULTIPLIER, FLAT_RATE, or COMPOUND"
    )
    
    multiplier = serializers.DecimalField(
        max_digits=5,
        decimal_places=2,
        default=Decimal('2.0'),
        required=False,
        help_text="Multiplier for MULTIPLIER or COMPOUND types (e.g., 2.0 for 2x rate)"
    )
    
    flat_rate_per_hour = serializers.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=Decimal('0'),
        required=False,
        help_text="Flat rate per overdue hour (NPR) for FLAT_RATE or COMPOUND types"
    )
    
    grace_period_minutes = serializers.IntegerField(
        default=0,
        required=False,
        min_value=0,
        help_text="Minutes before late charges start (0 = immediate)"
    )
    
    max_daily_rate = serializers.DecimalField(
        max_digits=10,
        decimal_places=2,
        required=False,
        allow_null=True,
        help_text="Maximum late fee per day (NPR) - leave empty for no limit"
    )
    
    is_active = serializers.BooleanField(
        default=True,
        required=False,
        help_text="Whether this configuration is currently active"
    )
    
    applicable_package_types = serializers.ListField(
        child=serializers.CharField(),
        required=False,
        default=list,
        help_text="Limit to specific package types (empty = all packages)"
    )
    
    metadata = serializers.JSONField(
        required=False,
        default=dict,
        help_text="Additional metadata for this configuration"
    )
    
    def validate(self, data):
        """Validate late fee configuration data"""
        fee_type = data.get('fee_type')
        multiplier = data.get('multiplier', Decimal('2.0'))
        flat_rate = data.get('flat_rate_per_hour', Decimal('0'))
        
        # Validate MULTIPLIER type
        if fee_type == 'MULTIPLIER':
            if multiplier <= 0:
                raise serializers.ValidationError({
                    'multiplier': 'Multiplier must be greater than 0 for MULTIPLIER fee type'
                })
        
        # Validate FLAT_RATE type
        elif fee_type == 'FLAT_RATE':
            if flat_rate <= 0:
                raise serializers.ValidationError({
                    'flat_rate_per_hour': 'Flat rate must be greater than 0 for FLAT_RATE fee type'
                })
        
        # Validate COMPOUND type
        elif fee_type == 'COMPOUND':
            if multiplier <= 0 or flat_rate <= 0:
                raise serializers.ValidationError({
                    'multiplier': 'Both multiplier and flat rate must be greater than 0 for COMPOUND fee type',
                    'flat_rate_per_hour': 'Both multiplier and flat rate must be greater than 0 for COMPOUND fee type'
                })
        
        # Validate max_daily_rate if provided
        max_daily = data.get('max_daily_rate')
        if max_daily is not None and max_daily <= 0:
            raise serializers.ValidationError({
                'max_daily_rate': 'Maximum daily rate must be greater than 0 or null'
            })
        
        # Validate grace period
        grace_period = data.get('grace_period_minutes', 0)
        if grace_period < 0:
            raise serializers.ValidationError({
                'grace_period_minutes': 'Grace period cannot be negative'
            })
        
        return data



class UpdateLateFeeConfigurationSerializer(serializers.Serializer):
    """Serializer for updating an existing late fee configuration"""
    
    name = serializers.CharField(
        max_length=100,
        required=False,
        help_text="Update configuration name"
    )
    
    fee_type = serializers.ChoiceField(
        choices=LateFeeConfiguration.FEE_TYPE_CHOICES,
        required=False,
        help_text="Update fee calculation method"
    )
    
    multiplier = serializers.DecimalField(
        max_digits=5,
        decimal_places=2,
        required=False,
        help_text="Update multiplier value"
    )
    
    flat_rate_per_hour = serializers.DecimalField(
        max_digits=10,
        decimal_places=2,
        required=False,
        help_text="Update flat rate per hour"
    )
    
    grace_period_minutes = serializers.IntegerField(
        required=False,
        min_value=0,
        help_text="Update grace period"
    )
    
    max_daily_rate = serializers.DecimalField(
        max_digits=10,
        decimal_places=2,
        required=False,
        allow_null=True,
        help_text="Update maximum daily rate"
    )
    
    is_active = serializers.BooleanField(
        required=False,
        help_text="Activate or deactivate this configuration"
    )
    
    applicable_package_types = serializers.ListField(
        child=serializers.CharField(),
        required=False,
        help_text="Update applicable package types"
    )
    
    metadata = serializers.JSONField(
        required=False,
        help_text="Update metadata"
    )
    
    def validate(self, data):
        """Validate update data"""
        # Only validate if values are being updated
        if 'multiplier' in data and data['multiplier'] is not None:
            if data['multiplier'] <= 0:
                raise serializers.ValidationError({
                    'multiplier': 'Multiplier must be greater than 0'
                })
        
        if 'flat_rate_per_hour' in data and data['flat_rate_per_hour'] is not None:
            if data['flat_rate_per_hour'] < 0:
                raise serializers.ValidationError({
                    'flat_rate_per_hour': 'Flat rate cannot be negative'
                })
        
        if 'max_daily_rate' in data and data['max_daily_rate'] is not None:
            if data['max_daily_rate'] <= 0:
                raise serializers.ValidationError({
                    'max_daily_rate': 'Maximum daily rate must be greater than 0 or null'
                })
        
        if 'grace_period_minutes' in data and data['grace_period_minutes'] is not None:
            if data['grace_period_minutes'] < 0:
                raise serializers.ValidationError({
                    'grace_period_minutes': 'Grace period cannot be negative'
                })
        
        return data



class ActivateLateFeeConfigurationSerializer(serializers.Serializer):
    """Serializer for activating a late fee configuration"""
    
    deactivate_others = serializers.BooleanField(
        default=True,
        required=False,
        help_text="Automatically deactivate other configurations (recommended)"
    )



class LateFeeCalculationTestSerializer(serializers.Serializer):
    """Serializer for testing late fee calculation"""
    
    configuration_id = serializers.UUIDField(
        required=True,
        help_text="ID of the late fee configuration to test"
    )
    
    normal_rate_per_minute = serializers.DecimalField(
        max_digits=10,
        decimal_places=2,
        required=True,
        help_text="Normal rental rate per minute (NPR)"
    )
    
    overdue_minutes = serializers.IntegerField(
        required=True,
        min_value=0,
        help_text="Number of minutes the rental is overdue"
    )
    
    def validate_normal_rate_per_minute(self, value):
        """Validate normal rate"""
        if value <= 0:
            raise serializers.ValidationError("Normal rate must be greater than 0")
        return value


