"""
Kyc Serializers
Auto-generated by split_serializer.py
"""

from __future__ import annotations
from rest_framework import serializers


class UpdateKYCStatusSerializer(serializers.Serializer):
    """Serializer for updating KYC status"""
    status = serializers.ChoiceField(choices=['APPROVED', 'REJECTED'])
    rejection_reason = serializers.CharField(
        max_length=500,
        required=False,
        allow_blank=True,
        help_text="Required when status is REJECTED"
    )
    
    def validate(self, data):
        """Validate that rejection_reason is provided when status is REJECTED"""
        if data['status'] == 'REJECTED' and not data.get('rejection_reason'):
            raise serializers.ValidationError({
                'rejection_reason': 'This field is required when rejecting KYC'
            })
        return data


