"""
Notification Serializers
Auto-generated by split_serializer.py
"""

from __future__ import annotations
from rest_framework import serializers


class BroadcastMessageSerializer(serializers.Serializer):
    """Serializer for broadcasting messages"""
    title = serializers.CharField(max_length=200)
    message = serializers.CharField(max_length=1000)
    target_audience = serializers.ChoiceField(choices=[
        'ALL', 'ACTIVE', 'PREMIUM', 'NEW', 'INACTIVE'
    ])
    send_push = serializers.BooleanField(default=True)
    send_email = serializers.BooleanField(default=False)


