"""
Rental Serializers
Auto-generated by split_serializer.py
"""

from __future__ import annotations
from api.rentals.models import RentalPackage
from api.rentals.models import RentalPackage
from rest_framework import serializers


class RentalsOverTimeQuerySerializer(serializers.Serializer):
    """Query parameters for rentals over time analytics"""
    period = serializers.ChoiceField(
        choices=['daily', 'weekly', 'monthly'],
        required=True,
        help_text="Aggregation period: daily, weekly, or monthly"
    )
    start_date = serializers.DateField(
        required=False,
        help_text="Start date (default: 30 days ago)"
    )
    end_date = serializers.DateField(
        required=False,
        help_text="End date (default: today)"
    )
    status = serializers.ChoiceField(
        choices=['PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'OVERDUE'],
        required=False,
        help_text="Filter by rental status"
    )



class RentalChartDataSerializer(serializers.Serializer):
    """Single data point for rentals chart"""
    date = serializers.DateField()
    label = serializers.CharField()
    total = serializers.IntegerField()
    completed = serializers.IntegerField()
    active = serializers.IntegerField()
    pending = serializers.IntegerField()
    cancelled = serializers.IntegerField()
    overdue = serializers.IntegerField()



class RentalsSummarySerializer(serializers.Serializer):
    """Summary statistics for rentals over time"""
    avg_per_period = serializers.FloatField()
    peak_date = serializers.DateField(allow_null=True)
    peak_count = serializers.IntegerField()



class RentalsOverTimeResponseSerializer(serializers.Serializer):
    """Response format for rentals over time endpoint"""
    period = serializers.CharField()
    start_date = serializers.DateField()
    end_date = serializers.DateField()
    total_rentals = serializers.IntegerField()
    chart_data = RentalChartDataSerializer(many=True)
    summary = RentalsSummarySerializer()



class AdminRentalIssueSerializer(serializers.Serializer):
    """Serializer for listing rental issues"""
    id = serializers.UUIDField(read_only=True)
    rental_code = serializers.CharField(source='rental.rental_code', read_only=True)
    user_email = serializers.EmailField(source='rental.user.email', read_only=True)
    user_name = serializers.CharField(source='rental.user.username', read_only=True)
    issue_type = serializers.CharField(read_only=True)
    description = serializers.CharField(read_only=True)
    status = serializers.CharField(read_only=True)
    images = serializers.JSONField(read_only=True)
    reported_at = serializers.DateTimeField(read_only=True)
    resolved_at = serializers.DateTimeField(read_only=True)
    
    # Rental details
    station_name = serializers.CharField(source='rental.station.station_name', read_only=True, allow_null=True)
    power_bank_serial = serializers.CharField(source='rental.power_bank.serial_number', read_only=True, allow_null=True)



class AdminRentalIssueDetailSerializer(serializers.Serializer):
    """Serializer for detailed rental issue view"""
    id = serializers.UUIDField(read_only=True)
    issue_type = serializers.CharField(read_only=True)
    description = serializers.CharField(read_only=True)
    status = serializers.CharField(read_only=True)
    images = serializers.JSONField(read_only=True)
    reported_at = serializers.DateTimeField(read_only=True)
    resolved_at = serializers.DateTimeField(read_only=True)
    
    # Rental details
    rental = serializers.SerializerMethodField()
    user = serializers.SerializerMethodField()
    
    def get_rental(self, obj):
        return {
            'id': str(obj.rental.id),
            'rental_code': obj.rental.rental_code,
            'status': obj.rental.status,
            'started_at': obj.rental.started_at,
            'ended_at': obj.rental.ended_at,
            'station': {
                'id': str(obj.rental.station.id),
                'name': obj.rental.station.station_name,
                'serial_number': obj.rental.station.serial_number
            } if obj.rental.station else None,
            'return_station': {
                'id': str(obj.rental.return_station.id),
                'name': obj.rental.return_station.station_name,
                'serial_number': obj.rental.return_station.serial_number
            } if obj.rental.return_station else None,
            'power_bank': {
                'id': str(obj.rental.power_bank.id),
                'serial_number': obj.rental.power_bank.serial_number
            } if obj.rental.power_bank else None
        }
    
    def get_user(self, obj):
        return {
            'id': str(obj.rental.user.id),
            'email': obj.rental.user.email,
            'username': obj.rental.user.username,
            'phone_number': obj.rental.user.phone_number
        }



class UpdateRentalIssueSerializer(serializers.Serializer):
    """Serializer for updating rental issue status"""
    status = serializers.ChoiceField(
        choices=['REPORTED', 'RESOLVED'],
        required=True
    )
    notes = serializers.CharField(
        required=False,
        allow_blank=True,
        max_length=500
    )



class AdminRentalPackageListSerializer(serializers.Serializer):
    """Serializer for rental package list filters"""
    is_active = serializers.BooleanField(required=False, allow_null=True, default=None)
    package_type = serializers.ChoiceField(
        choices=['HOURLY', 'DAILY', 'WEEKLY', 'MONTHLY'],
        required=False
    )
    payment_model = serializers.ChoiceField(
        choices=['PREPAID', 'POSTPAID'],
        required=False
    )
    search = serializers.CharField(required=False)
    page = serializers.IntegerField(default=1, min_value=1)
    page_size = serializers.IntegerField(default=20, min_value=1, max_value=100)



class AdminRentalPackageSerializer(serializers.ModelSerializer):
    """Serializer for rental package details"""
    duration_display = serializers.SerializerMethodField()
    
    class Meta:
        model = RentalPackage
        fields = [
            'id', 'name', 'description', 'duration_minutes', 'price',
            'package_type', 'payment_model', 'is_active', 'package_metadata',
            'duration_display', 'created_at', 'updated_at'
        ]
        read_only_fields = ['id', 'created_at', 'updated_at']
    
    def get_duration_display(self, obj):
        """Get human-readable duration"""
        minutes = obj.duration_minutes
        if minutes < 60:
            return f"{minutes} minutes"
        elif minutes < 1440:  # Less than 24 hours
            hours = minutes // 60
            remaining_minutes = minutes % 60
            if remaining_minutes == 0:
                return f"{hours} hour{'s' if hours > 1 else ''}"
            else:
                return f"{hours}h {remaining_minutes}m"
        else:  # Days
            days = minutes // 1440
            return f"{days} day{'s' if days > 1 else ''}"



class CreateRentalPackageSerializer(serializers.Serializer):
    """Serializer for creating rental package"""
    name = serializers.CharField(max_length=100)
    description = serializers.CharField(max_length=255)
    duration_minutes = serializers.IntegerField(min_value=1)
    price = serializers.DecimalField(max_digits=10, decimal_places=2, min_value=0)
    package_type = serializers.ChoiceField(
        choices=['HOURLY', 'DAILY', 'WEEKLY', 'MONTHLY']
    )
    payment_model = serializers.ChoiceField(
        choices=['PREPAID', 'POSTPAID']
    )
    is_active = serializers.BooleanField(default=True)
    package_metadata = serializers.JSONField(default=dict, required=False)



class UpdateRentalPackageSerializer(serializers.Serializer):
    """Serializer for updating rental package"""
    name = serializers.CharField(max_length=100, required=False)
    description = serializers.CharField(max_length=255, required=False)
    duration_minutes = serializers.IntegerField(min_value=1, required=False)
    price = serializers.DecimalField(max_digits=10, decimal_places=2, min_value=0, required=False)
    package_type = serializers.ChoiceField(
        choices=['HOURLY', 'DAILY', 'WEEKLY', 'MONTHLY'],
        required=False
    )
    payment_model = serializers.ChoiceField(
        choices=['PREPAID', 'POSTPAID'],
        required=False
    )
    is_active = serializers.BooleanField(required=False)
    package_metadata = serializers.JSONField(required=False)



class AdminRentalSerializer(serializers.Serializer):
    """Serializer for listing rentals"""
    id = serializers.UUIDField(read_only=True)
    rental_code = serializers.CharField()
    status = serializers.CharField()
    payment_status = serializers.CharField()
    
    # User info
    user_id = serializers.IntegerField(source='user.id')
    username = serializers.CharField(source='user.username')
    user_phone = serializers.CharField(source='user.phone_number')
    
    # Station info
    station_id = serializers.UUIDField(source='station.id')
    station_name = serializers.CharField(source='station.station_name')
    station_serial = serializers.CharField(source='station.serial_number')
    
    # Return station info
    return_station_id = serializers.UUIDField(source='return_station.id', allow_null=True)
    return_station_name = serializers.CharField(source='return_station.station_name', allow_null=True)
    
    # PowerBank info
    powerbank_serial = serializers.CharField(source='power_bank.serial_number', allow_null=True)
    
    # Package info
    package_name = serializers.CharField(source='package.name')
    package_duration = serializers.IntegerField(source='package.duration_minutes')
    
    # Timestamps and amounts
    started_at = serializers.DateTimeField()
    ended_at = serializers.DateTimeField(allow_null=True)
    due_at = serializers.DateTimeField()
    amount_paid = serializers.DecimalField(max_digits=10, decimal_places=2)
    overdue_amount = serializers.DecimalField(max_digits=10, decimal_places=2)
    
    is_returned_on_time = serializers.BooleanField()
    created_at = serializers.DateTimeField(read_only=True)



class AdminRentalDetailSerializer(serializers.Serializer):
    """Serializer for rental detail view"""
    id = serializers.UUIDField(read_only=True)
    rental_code = serializers.CharField()
    status = serializers.CharField()
    payment_status = serializers.CharField()
    
    # User info
    user = serializers.SerializerMethodField()
    
    # Station info
    station = serializers.SerializerMethodField()
    return_station = serializers.SerializerMethodField()
    
    # Slot and PowerBank
    slot_number = serializers.IntegerField(source='slot.slot_number')
    powerbank = serializers.SerializerMethodField()
    
    # Package
    package = serializers.SerializerMethodField()
    
    # Timestamps
    started_at = serializers.DateTimeField()
    ended_at = serializers.DateTimeField(allow_null=True)
    due_at = serializers.DateTimeField()
    created_at = serializers.DateTimeField()
    updated_at = serializers.DateTimeField()
    
    # Amounts
    amount_paid = serializers.DecimalField(max_digits=10, decimal_places=2)
    overdue_amount = serializers.DecimalField(max_digits=10, decimal_places=2)
    
    # Flags
    is_returned_on_time = serializers.BooleanField()
    timely_return_bonus_awarded = serializers.BooleanField()
    
    # Extensions and issues
    extensions_count = serializers.SerializerMethodField()
    issues_count = serializers.SerializerMethodField()
    
    # Metadata
    rental_metadata = serializers.JSONField()
    
    def get_user(self, obj):
        return {
            'id': obj.user.id,
            'username': obj.user.username,
            'phone_number': obj.user.phone_number,
            'email': obj.user.email
        }
    
    def get_station(self, obj):
        return {
            'id': str(obj.station.id),
            'station_name': obj.station.station_name,
            'serial_number': obj.station.serial_number,
            'address': obj.station.address
        }
    
    def get_return_station(self, obj):
        if not obj.return_station:
            return None
        return {
            'id': str(obj.return_station.id),
            'station_name': obj.return_station.station_name,
            'serial_number': obj.return_station.serial_number,
            'address': obj.return_station.address
        }
    
    def get_powerbank(self, obj):
        if not obj.power_bank:
            return None
        return {
            'id': str(obj.power_bank.id),
            'serial_number': obj.power_bank.serial_number,
            'model': obj.power_bank.model,
            'battery_level': obj.power_bank.battery_level
        }
    
    def get_package(self, obj):
        return {
            'id': str(obj.package.id),
            'name': obj.package.name,
            'duration_minutes': obj.package.duration_minutes,
            'price': str(obj.package.price)
        }
    
    def get_extensions_count(self, obj):
        return obj.extensions.count() if hasattr(obj, 'extensions') else 0
    
    def get_issues_count(self, obj):
        return obj.issues.count() if hasattr(obj, 'issues') else 0


