"""
User Serializers
Auto-generated by split_serializer.py
"""

from __future__ import annotations
from api.admin.models import AdminProfile
from decimal import Decimal
from decimal import Decimal
from rest_framework import serializers


class AdminProfileSerializer(serializers.ModelSerializer):
    """Serializer for admin profiles"""
    username = serializers.CharField(source='user.username', read_only=True)
    email = serializers.CharField(source='user.email', read_only=True)
    created_by_username = serializers.CharField(source='created_by.username', read_only=True)
    is_super_admin = serializers.BooleanField(read_only=True)
    
    class Meta:
        model = AdminProfile
        fields = [
            'id', 'role', 'is_active', 'is_super_admin',
            'created_at', 'updated_at',
            'username', 'email', 'created_by_username'
        ]
        read_only_fields = ['id', 'created_at', 'updated_at']



class AdminProfileCreateSerializer(serializers.Serializer):
    """Serializer for creating admin profiles"""
    user = serializers.IntegerField()
    role = serializers.ChoiceField(choices=AdminProfile.RoleChoices.choices)
    password = serializers.CharField(write_only=True, required=True, min_length=8, max_length=128)



class AdminProfileUpdateSerializer(serializers.Serializer):
    """Serializer for updating admin profile (role, password, is_active)"""
    role = serializers.ChoiceField(
        choices=AdminProfile.RoleChoices.choices,
        required=False,
        help_text="Update admin role"
    )
    new_password = serializers.CharField(
        min_length=8,
        max_length=128,
        required=False,
        write_only=True,
        help_text="Update password (minimum 8 characters)"
    )
    is_active = serializers.BooleanField(
        required=False,
        help_text="Activate (true) or deactivate (false) admin"
    )
    reason = serializers.CharField(
        max_length=500,
        required=False,
        allow_blank=True,
        help_text="Reason for deactivation/activation"
    )



class AdminProfileActionSerializer(serializers.Serializer):
    """Serializer for admin profile actions (activate/deactivate)"""
    reason = serializers.CharField(max_length=500, required=False, allow_blank=True)



class AdminUserListSerializer(serializers.Serializer):
    """Serializer for user list filters"""
    status = serializers.CharField(required=False)
    search = serializers.CharField(required=False)
    start_date = serializers.DateTimeField(required=False)
    end_date = serializers.DateTimeField(required=False)
    page = serializers.IntegerField(default=1, min_value=1)
    page_size = serializers.IntegerField(default=20, min_value=1, max_value=100)



class UpdateUserStatusSerializer(serializers.Serializer):
    """Serializer for updating user status"""
    status = serializers.ChoiceField(choices=['ACTIVE', 'BANNED', 'INACTIVE'])
    reason = serializers.CharField(max_length=500)



class AddUserBalanceSerializer(serializers.Serializer):
    """Serializer for adding user balance"""
    amount = serializers.DecimalField(max_digits=10, decimal_places=2, min_value=Decimal('0.01'))
    reason = serializers.CharField(max_length=500)



class TransactionUserSerializer(serializers.Serializer):
    """User info in transaction response"""
    id = serializers.UUIDField()
    username = serializers.CharField()
    email = serializers.EmailField()


