"""
Withdrawal Serializers
Auto-generated by split_serializer.py
"""

from __future__ import annotations
from rest_framework import serializers


class WithdrawalFiltersSerializer(serializers.Serializer):
    """Serializer for withdrawal filters"""
    status = serializers.ChoiceField(
        choices=['REQUESTED', 'APPROVED', 'PROCESSING', 'COMPLETED', 'REJECTED', 'CANCELLED'],
        required=False,
        help_text="Filter by withdrawal status"
    )
    payment_method = serializers.CharField(
        required=False,
        max_length=100,
        help_text="Filter by payment method name (e.g., 'eSewa', 'Khalti')"
    )
    search = serializers.CharField(
        required=False,
        max_length=200,
        help_text="Search by internal reference, username, or email"
    )
    start_date = serializers.DateTimeField(
        required=False,
        help_text="Filter withdrawals requested after this date"
    )
    end_date = serializers.DateTimeField(
        required=False,
        help_text="Filter withdrawals requested before this date"
    )
    page = serializers.IntegerField(
        default=1,
        min_value=1,
        help_text="Page number"
    )
    page_size = serializers.IntegerField(
        default=20,
        min_value=1,
        max_value=100,
        help_text="Items per page (max 100)"
    )



class ProcessWithdrawalSerializer(serializers.Serializer):
    """Serializer for processing withdrawal"""
    action = serializers.ChoiceField(choices=['APPROVE', 'REJECT'])
    admin_notes = serializers.CharField(max_length=1000, required=False, allow_blank=True)
    
    def validate_admin_notes(self, value):
        action = self.initial_data.get('action')
        if action == 'REJECT' and (not value or len(value.strip()) < 5):
            raise serializers.ValidationError("Admin notes are required for rejection (minimum 5 characters)")
        return value.strip() if value else ''


