# Generated by Django 5.2.5 on 2025-10-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_password_otp_auth'),
    ]

    operations = [
    ]
