"""
Services package for users app
============================================================

This package contains all service classes organized by functionality.
Maintains backward compatibility by re-exporting all services.

Auto-generated by Service Separator
Date: 2025-10-18 22:53:34
"""
from __future__ import annotations

from .auth_service import AuthService
from .user_profile_service import UserProfileService
from .user_kyc_service import UserKYCService
from .user_device_service import UserDeviceService


# Backward compatibility - all services available at package level
__all__ = [
    "AuthService",
    "UserDeviceService",
    "UserKYCService",
    "UserProfileService",
]
