"""
Service for device management
============================================================

This module contains service classes for service for device management.

Auto-generated by Service Separator
Date: 2025-10-18 22:53:34
"""
from __future__ import annotations

from __future__ import annotations
import os
import uuid
from typing import Dict, Any, Optional
from decimal import Decimal
from django.db import transaction
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.core.cache import cache
from rest_framework_simplejwt.tokens import RefreshToken
from api.common.services.base import BaseService, ServiceException
from api.common.utils.helpers import (
    generate_random_code, 
    generate_unique_code,
    validate_phone_number,
    get_client_ip
)
from api.users.models import User, UserProfile, UserKYC, UserDevice, UserPoints, UserAuditLog
from api.payments.models import Wallet
from api.notifications.services import notify

class UserDeviceService(BaseService):
    """Service for device management"""
    
    @transaction.atomic
    def register_device(self, user: User, validated_data: Dict[str, Any]) -> UserDevice:
        """Register or update user device"""
        try:
            device, created = UserDevice.objects.update_or_create(
                user=user,
                device_id=validated_data['device_id'],
                defaults=validated_data
            )
            
            action = "registered" if created else "updated"
            self.log_info(f"Device {action} for user: {user.username}")
            
            return device
            
        except Exception as e:
            self.handle_service_error(e, "Failed to register device")
