# Generated by Django 5.2.5 on 2025-10-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Notes from admin regarding the refund', null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.TextField(help_text='Reason for refund request'),
        ),
    ]
