# Generated by Django 5.2.5 on 2025-10-07 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_refund_admin_notes_alter_refund_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='paymentintent',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.transaction'),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
