# Generated by Django 5.2.5 on 2025-10-08 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_transaction_payment_method_and_more'),
    ]

    operations = [
    ]
