"""
Services package for admin app
============================================================

This package contains all service classes organized by functionality.
Maintains backward compatibility by re-exporting all services.

Auto-generated by Service Separator
Date: 2025-10-18 23:39:20
Updated: 2025-11-06 - Added AdminPaymentService
"""
from __future__ import annotations

from .admin_user_service import AdminUserService
from .admin_station_service import AdminStationService
from .admin_analytics_service import AdminAnalyticsService
from .admin_refund_service import AdminRefundService
from .admin_notification_service import AdminNotificationService
from .admin_system_service import AdminSystemService
from .admin_content_service import AdminContentService
from .admin_withdrawal_service import AdminWithdrawalService
from .admin_profile_service import AdminProfileService
from .admin_rental_service import AdminRentalService
from .admin_payment_service import AdminPaymentService
from .late_fee_service import LateFeeConfigurationService


# Backward compatibility - all services available at package level
__all__ = [
    "AdminAnalyticsService",
    "AdminContentService",
    "AdminNotificationService",
    "AdminPaymentService",
    "AdminProfileService",
    "AdminRefundService",
    "AdminRentalService",
    "AdminStationService",
    "AdminSystemService",
    "AdminUserService",
    "AdminWithdrawalService",
    "LateFeeConfigurationService",
]

