"""
Services package for admin app
============================================================

This package contains all service classes organized by functionality.
Maintains backward compatibility by re-exporting all services.

Auto-generated by Service Separator
Date: 2025-10-18 23:39:20
"""
from __future__ import annotations

from .admin_user_service import AdminUserService
from .admin_station_service import AdminStationService
from .admin_analytics_service import AdminAnalyticsService
from .admin_refund_service import AdminRefundService
from .admin_notification_service import AdminNotificationService
from .admin_system_service import AdminSystemService
from .admin_content_service import AdminContentService
from .admin_withdrawal_service import AdminWithdrawalService
from .package_service import PackageService
from .coupon_service import CouponService


# Backward compatibility - all services available at package level
__all__ = [
    "AdminAnalyticsService",
    "AdminContentService",
    "AdminNotificationService",
    "AdminRefundService",
    "AdminStationService",
    "AdminSystemService",
    "AdminUserService",
    "AdminWithdrawalService",
    "PackageService",
    "CouponService",
]
