# Generated by Django 5.2.5 on 2025-09-06 19:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental_code', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=50)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField()),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overdue_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_returned_on_time', models.BooleanField(default=False)),
                ('timely_return_bonus_awarded', models.BooleanField(default=False)),
                ('rental_metadata', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Rental',
                'verbose_name_plural': 'Rentals',
                'db_table': 'rentals',
            },
        ),
        migrations.CreateModel(
            name='RentalExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extended_minutes', models.IntegerField()),
                ('extension_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extended_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rental Extension',
                'verbose_name_plural': 'Rental Extensions',
                'db_table': 'rental_extensions',
            },
        ),
        migrations.CreateModel(
            name='RentalIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_type', models.CharField(choices=[('POWER_BANK_DAMAGED', 'Power Bank Damaged'), ('POWER_BANK_LOST', 'Power Bank Lost'), ('CHARGING_ISSUE', 'Charging Issue'), ('RETURN_ISSUE', 'Return Issue')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('images', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('RESOLVED', 'Resolved')], default='REPORTED', max_length=50)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rental Issue',
                'verbose_name_plural': 'Rental Issues',
                'db_table': 'rental_issues',
            },
        ),
        migrations.CreateModel(
            name='RentalLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rental Location',
                'verbose_name_plural': 'Rental Locations',
                'db_table': 'rental_locations',
            },
        ),
        migrations.CreateModel(
            name='RentalPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('duration_minutes', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_type', models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=50)),
                ('payment_model', models.CharField(choices=[('PREPAID', 'Prepaid'), ('POSTPAID', 'Postpaid')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('package_metadata', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Rental Package',
                'verbose_name_plural': 'Rental Packages',
                'db_table': 'rental_packages',
                'ordering': ['price'],
            },
        ),
    ]
