# Generated by Django 5.2.5 on 2025-09-06 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='power_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stations.powerbank'),
        ),
        migrations.AddField(
            model_name='rental',
            name='return_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_rentals', to='stations.station'),
        ),
        migrations.AddField(
            model_name='rental',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.stationslot'),
        ),
        migrations.AddField(
            model_name='rental',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='stations.station'),
        ),
        migrations.AddField(
            model_name='rental',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalextension',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalextension',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='rentals.rental'),
        ),
        migrations.AddField(
            model_name='rentalissue',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='rentals.rental'),
        ),
        migrations.AddField(
            model_name='rentallocation',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='rentals.rental'),
        ),
        migrations.AddField(
            model_name='rentalextension',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.rentalpackage'),
        ),
        migrations.AddField(
            model_name='rental',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.rentalpackage'),
        ),
    ]
