# Generated by Django on 2025-01-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userachievement',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['user', 'is_unlocked', 'is_claimed'], name='idx_user_unlock_claim'),
        ),
    ]
