# Generated by Django 5.2.5 on 2025-10-18 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationmedia',
            name='media_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.mediaupload'),
        ),
    ]
