# Generated by Django 5.2.5 on 2025-11-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_stationmedia_media_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
