# Generated by Django 5.2.5 on 2025-11-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_add_is_deleted_to_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='closing_time',
            field=models.TimeField(blank=True, help_text='Station closing time (e.g., 21:00)', null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='opening_time',
            field=models.TimeField(blank=True, help_text='Station opening time (e.g., 09:00)', null=True),
        ),
    ]
