# Generated by Django 5.2.5 on 2025-11-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_add_opening_closing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='description',
            field=models.TextField(blank=True, help_text='Station description and additional information', null=True),
        ),
    ]
